name: testsuite

on:
  workflow_run:
    workflows: ["continuous-integration"]
    types:
      - completed

jobs:
  macos-latest:
    runs-on: macos-latest
    steps:
    - name: Download artifact
      uses: dawidd6/action-download-artifact@v2
      with:
        workflow: ${{ github.event.workflow_run.workflow_id }}
        workflow_conclusion: success
